name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pip install poetry  # poetry needs to exists before setup-python action
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry poethepoet
        poetry install
    - name: Lint with ruff
      run: poe style
    - name: Test with pytest
      run: poe test
    - name: Test with mypy
      run: poe typing
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
